// https://developer.twitter.com/en/docs/tweets/data-dictionary/overview/tweet-object
// https://developer.twitter.com/en/docs/tweets/data-dictionary/overview/intro-to-tweet-json
const exampleTweet = { created_at: 'Mon Feb 19 14:09:42 +0000 2018',
  id: 965589211100405800,
  id_str: '965589211100405761',
  text: 'Africa and the diaspora was well represented at our screening yesterday! We hope to see more of that this Thursday… https://t.co/TZscyW8ada',
  display_text_range: [ 0, 140 ],
  source: '<a href="http://twitter.com/download/iphone" rel="nofollow">Twitter for iPhone</a>',
  truncated: true,
  in_reply_to_status_id: null,
  in_reply_to_status_id_str: null,
  in_reply_to_user_id: null,
  in_reply_to_user_id_str: null,
  in_reply_to_screen_name: null,
  user:
   { id: 842595566,
     id_str: '842595566',
     name: 'ECAC Auxiliary Board',
     screen_name: 'chicagohabeshas',
     location: 'Chicago, IL',
     url: 'https://www.eventbrite.com/e/african-professionals-networking-mixer-tickets-42887175697?aff=eac2',
     description: 'Official Twitter account of the Ethiopian Community Association of Chicago, Auxiliary Board #Habesha #Chicago #Ethiopia #YoungProfessionals #Volunteer',     translator_type: 'none',
     protected: false,
     verified: false,
     followers_count: 91,
     friends_count: 119,
     listed_count: 12,
     favourites_count: 27,
     statuses_count: 333,
     created_at: 'Sun Sep 23 23:37:25 +0000 2012',
     utc_offset: -21600,
     time_zone: 'Central Time (US & Canada)',
     geo_enabled: true,
     lang: 'en',
     contributors_enabled: false,
     is_translator: false,
     profile_background_color: '131516',
     profile_background_image_url: 'http://pbs.twimg.com/profile_background_images/577545850399801344/2K2oR_4S.png',
     profile_background_image_url_https: 'https://pbs.twimg.com/profile_background_images/577545850399801344/2K2oR_4S.png',
     profile_background_tile: true,
     profile_link_color: 'E81C4F',
     profile_sidebar_border_color: '000000',
     profile_sidebar_fill_color: 'DDEEF6',
     profile_text_color: '333333',
     profile_use_background_image: true,
     profile_image_url: 'http://pbs.twimg.com/profile_images/961823523139239936/_sj84R-8_normal.jpg',
     profile_image_url_https: 'https://pbs.twimg.com/profile_images/961823523139239936/_sj84R-8_normal.jpg',
     profile_banner_url: 'https://pbs.twimg.com/profile_banners/842595566/1518705533',
     default_profile: false,
     default_profile_image: false,
     following: null,
     follow_request_sent: null,
     notifications: null },
  geo: null,
  coordinates: null,
  place: null,
  contributors: null,
  is_quote_status: false,
  extended_tweet:
   { full_text: 'Africa and the diaspora was well represented at our screening yesterday! We hope to see more of that this Thursday as East, West, North &amp; South unite to bring you our African Professionals Networking Mixer from 6pm-10pm at @safariloungechicago! 2 levels, 2 DJs &amp; $5 drink specials https://t.co/EQqFcnVDBf',
     display_text_range: [ 0, 288 ],
     entities:
      { hashtags: [],
        urls: [],
        user_mentions: [],
        symbols: [],
        media: [Array] },
     extended_entities: { media: [Array] } },
  quote_count: 0,
  reply_count: 0,
  retweet_count: 0,
  favorite_count: 0,
  entities:
   { hashtags: [],
     urls: [ [Object] ],
     user_mentions: [],
     symbols: [] },
  favorited: false,
  retweeted: false,
  possibly_sensitive: false,
  filter_level: 'low',
  lang: 'en',
  timestamp_ms: '1519049382363' }